FROM python:3.9-slim

COPY ./src/api/requirements.txt /usr/requirements.txt
COPY ./src /usr/src
COPY ./models /usr/models
COPY ./data/processed /usr/data/processed

WORKDIR /usr

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "src/api/main.py" ]