FROM python:3.9-slim

COPY ./requirements.txt /usr/requirements.txt
COPY ./src /usr/src
COPY ./models /usr/models
COPY ./data/processed /usr/data/processed

ARG BASIC_AUTH_USERNAME_ARG
ARG BASIC_AUTH_PASSWORD_ARG

ENV BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME_ARG
ENV BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD_ARG

WORKDIR /usr

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "src/api/main.py" ]


