services:
  ml-api:
    container_name: ml-api
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - server_api

  home:
    container_name: home
    build:
      context: .
      dockerfile: Dockerfile-home
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      API_URL: ${API_URL}
      API_PORT: ${API_PORT}
      PORT: 3000
    depends_on: 
      - ml-api
    ports:
      - "3000:3000"
    networks:
      - server_api

networks:
  server_api:
    driver: bridge

