services:
  ml-api:
    container_name: ml-api
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - server_api

  home:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      API_URL: ${API_URL}
      API_PORT: ${API_PORT}
      API_PATH: ${API_PATH}
    depends_on: 
      - ml-api
    ports:
      - "8501:8501"
    networks:
      - server_api

networks:
  server_api:
    driver: bridge

